// //1st question//
// var value = 1569;
//     sum = 0;

// while (value) {
//     sum += value % 10;
//     value = Math.floor(value / 10);
// }

// console.log(sum);
   
// //2nd question//
// let count = 0;
// let i = 0;

// while (count <= 10000) {
//     i++;
//     count = 5 ** i; 
// }

// console.log(count);

// //3rd question//
// let a =5;
// let b= 10;
// sum=0
// for(i=a;i<=10;i++){
//     if(i%2===0){
//         sum+=i
//     }
// // }
//     console.log(sum);














//Object//
const student = {
    name: "Pranesh",
    class: "sec B",
    height: 170,
    gender: "Male",
    colour: "white",
    age: 20,
    grades: [90, 85, 88, 80, 75],
    address: {
      street: "123 Main St",
      city: "New York"
    }
  };
student.age=21
console.log(student.age);


